<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:include filename="$(find craft_description)/urdf/common.xacro" />

  <xacro:arg name="square_hull" default="false"/>

	<xacro:if value="$(arg square_hull)">
		<xacro:property name="chassis_length" value="0.5"/>
		<xacro:property name="chassis_width" value="0.7"/>
		<xacro:property name="chassis_height" value="0.305"/>
	</xacro:if>

  <xacro:macro name="craft" params="prefix parent *origin">
    <!-- LINKS -->
    <!-- base link -->
    <link name="${prefix}base_link">
 
    </link>


    <!-- link 1 -->
    <link name="${prefix}hullassm">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <xacro:if value="$(arg square_hull)">
					  <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
				  </xacro:if>
          <xacro:unless value="$(arg square_hull)">
            <mesh filename="package://craft_description/meshes/craft/visual/hullassm.stl" />
          </xacro:unless>
        </geometry>
        <material name="hullassm_material">
				  <color rgba="0.24291 0.244006 0.250091 1.0" />
			  </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <xacro:if value="$(arg square_hull)">
					  <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
				  </xacro:if>
				  <xacro:unless value="$(arg square_hull)">
            <mesh filename="package://craft_description/meshes/craft/collision/hullassm.stl" />
          </xacro:unless>
        </geometry>
      </collision>
      <xacro:if value="$(arg square_hull)">
        <xacro:box_inertial mass="10" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
          <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0" />
        </xacro:box_inertial>
		  </xacro:if>
      <xacro:unless value="$(arg square_hull)">
        <inertial>
          <origin xyz="1.0307e-06 0.188008 0.124094" rpy="0 0 0" />
          <mass value="6.29782" />
          <inertia ixx="0.216502" ixy="-1.02604e-06" ixz="1.28468e-06" iyy="0.0821502"
            iyz="0.0297739" izz="0.237496" />
        </inertial>
      </xacro:unless>
    </link>
    <gazebo reference="hullassm">
      <material>Gazebo/DarkGrey</material>
    </gazebo>


    <!-- link 2 -->
    <link name="${prefix}propeller">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://craft_description/meshes/craft/visual/propeller.stl" />
        </geometry>
        <material name="propeller_material">
				  <color rgba="0.682353 0.333333 0.737255 1.0" />
			  </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://craft_description/meshes/craft/collision/propeller.stl"  />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="1.6644e-07 -8.74972e-08 -0.00131544" rpy="0 0 0" />
        <mass value="0.0252682" />
        <inertia ixx="1.02998e-05" ixy="4.84789e-11" ixz="7.4214e-11" iyy="1.02998e-05"
          iyz="5.65357e-11" izz="1.394e-05" />
		  </inertial>
    </link>
    <gazebo reference="propeller">
      <material>Gazebo/Purple</material>
    </gazebo>


    <!-- link 3 -->
    <link name="${prefix}topassm">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://craft_description/meshes/craft/visual/topassm.stl" />
        </geometry>
        <material name="topassm_material">
				  <color rgba="0.780424 0.75747 0.695877 1.0" />
			  </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://craft_description/meshes/craft/collision/topassm.stl"  />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0.2286 -0.367849 0.00346183" rpy="0 0 0" />
        <mass value="0.69925" />
        <inertia ixx="0.028029" ixy="-2.71051e-19" ixz="-2.03288e-20" iyy="0.0137782"
          iyz="-7.66504e-05" izz="0.0417123" />
		  </inertial>
    </link>
    <gazebo reference="topassm">
      <material>Gazebo/White</material>
    </gazebo>


    <!-- link 4 -->
    <link name="${prefix}servocargoassm">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://craft_description/meshes/craft/visual/servocargoassm.stl" />
        </geometry>
        <material name="servocargoassm_material">
				  <color rgba="0.621357 0.806496 0.907144 1.0" />
			  </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://craft_description/meshes/craft/collision/servocargoassm.stl"  />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="-2.57314e-10 0.0877782 -0.220495" rpy="0 0 0" />
        <mass value="8.22292" />
        <inertia ixx="0.17107" ixy="-2.11808e-10" ixz="6.43831e-10" iyy="0.215272"
          iyz="0.00150393" izz="0.0855135" />
		  </inertial>
    </link>
    <gazebo reference="servocargoassm">
      <material>Gazebo/Blue </material>
    </gazebo>


    <!-- link 5 -->
    <link name="${prefix}rudder">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://craft_description/meshes/craft/visual/rudder.stl" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://craft_description/meshes/craft/collision/rudder.stl" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="1.73472e-17 0.00323547 -0.179304" rpy="0 0 0" />
        <mass value="0.0651203" />
        <inertia ixx="0.000500832" ixy="3.75168e-21" ixz="6.55605e-23" iyy="0.00049688"
          iyz="1.16286e-05" izz="4.87634e-06" />
		  </inertial>
    </link>
    <gazebo reference="rudder">
      <material>Gazebo/Yellow</material>
    </gazebo>
    <!-- END LINKS -->


    <!-- JOINTS -->
    <!-- base_joint fixes base_link to the environment -->
    <joint name="${prefix}base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${prefix}base_link" />
    </joint>
    <!-- joint 1 -->
    <joint name="${prefix}hull_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}hullassm" />
    </joint>
    <!-- joint 2 -->
    <joint name="${prefix}propeller_joint" type="continuous">
		  <origin xyz="-2.11292e-18 0.385445 0.0889" rpy="1.5708 -0.187437 -3.49069e-15" />
      <parent link="${prefix}hullassm" />
      <child link="${prefix}propeller" />
      <axis xyz="0 0 1" />
    </joint>
    <!-- joint 3 -->
    <joint name="${prefix}hull_cover" type="fixed">
      <origin xyz="-0.2286 0.360045 0.3048" rpy="0 3.08149e-32 -4.62274e-32" />
      <parent link="${prefix}hullassm" />
      <child link="${prefix}topassm" />
      <axis xyz="0 0 1" />
    </joint>
    <!-- joint 4 -->
    <joint name="${prefix}hull_cargo" type="fixed">
		  <origin xyz="-2.77556e-17 0.3556 0.3048" rpy="-1.5708 -0 -4.62274e-32" />
      <parent link="${prefix}hullassm" />
      <child link="${prefix}servocargoassm" />
      <axis xyz="0 0 1" />
    </joint>
    <!-- joint 5 -->
    <joint name="${prefix}servo_joint" type="revolute">
      <origin xyz="3.43338e-16 -0.005715 0.074295" rpy="-1.5708 0 -1.03735e-13" />
      <parent link="${prefix}servocargoassm" />
      <child link="${prefix}rudder" />
      <axis xyz="0 0 1" />
      <!-- NOTE future try lower="${radians(-90)}" upper="${radians(90)}" -->
      <limit effort="0" lower="-1.5708" upper="1.5708" velocity="4.36" />
    </joint>
    <!-- END JOINTS -->

  </xacro:macro>
</robot>
